# Server Port
server:
  port: 8080

# Spring
spring:
  # Database
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    jdbc-url: jdbc:log4jdbc:mysql://175.197.109.105:3301/barogo_msa?&allowMultiQueries=true&characterEncoding=UTF-8
    username: barogo_tester
    password: gopos12#$

  # Ant Path Matcher
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# Logging
logging:
  config: classpath:logback-local.xml

# API
api:
  base:
    url: https://gopos.outlier.kr